package com.example.compose
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF00677D)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFB3EBFF)
val md_theme_light_onPrimaryContainer = Color(0xFF001F27)
val md_theme_light_secondary = Color(0xFF4B626A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCEE6F0)
val md_theme_light_onSecondaryContainer = Color(0xFF061E25)
val md_theme_light_tertiary = Color(0xFF595C7E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDFE0FF)
val md_theme_light_onTertiaryContainer = Color(0xFF151937)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFCFE)
val md_theme_light_onBackground = Color(0xFF191C1D)
val md_theme_light_surface = Color(0xFFFBFCFE)
val md_theme_light_onSurface = Color(0xFF191C1D)
val md_theme_light_surfaceVariant = Color(0xFFDBE4E8)
val md_theme_light_onSurfaceVariant = Color(0xFF40484B)
val md_theme_light_outline = Color(0xFF70787C)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F2)
val md_theme_light_inverseSurface = Color(0xFF2E3132)
val md_theme_light_inversePrimary = Color(0xFF59D5F8)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF00677D)
val md_theme_light_outlineVariant = Color(0xFFBFC8CC)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF59D5F8)
val md_theme_dark_onPrimary = Color(0xFF003642)
val md_theme_dark_primaryContainer = Color(0xFF004E5F)
val md_theme_dark_onPrimaryContainer = Color(0xFFB3EBFF)
val md_theme_dark_secondary = Color(0xFFB3CAD3)
val md_theme_dark_onSecondary = Color(0xFF1D343B)
val md_theme_dark_secondaryContainer = Color(0xFF344A52)
val md_theme_dark_onSecondaryContainer = Color(0xFFCEE6F0)
val md_theme_dark_tertiary = Color(0xFFC1C4EB)
val md_theme_dark_onTertiary = Color(0xFF2A2E4D)
val md_theme_dark_tertiaryContainer = Color(0xFF414465)
val md_theme_dark_onTertiaryContainer = Color(0xFFDFE0FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1D)
val md_theme_dark_onBackground = Color(0xFFE1E3E4)
val md_theme_dark_surface = Color(0xFF191C1D)
val md_theme_dark_onSurface = Color(0xFFE1E3E4)
val md_theme_dark_surfaceVariant = Color(0xFF40484B)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC8CC)
val md_theme_dark_outline = Color(0xFF899296)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1D)
val md_theme_dark_inverseSurface = Color(0xFFE1E3E4)
val md_theme_dark_inversePrimary = Color(0xFF00677D)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF59D5F8)
val md_theme_dark_outlineVariant = Color(0xFF40484B)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF007F99)
